"""поле username сменено на email

Revision ID: f9024001f178
Revises: e56ba921401a
Create Date: 2023-04-08 15:43:15.715170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9024001f178'
down_revision = 'e56ba921401a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
